# Generated by Django 6.0.1 on 2026-01-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Description',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Image',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
    ]
