# Generated by Django 6.0.1 on 2026-01-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_restaurant_description_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=255)),
                ('Image', models.ImageField(default='NULL', upload_to='')),
                ('Description', models.CharField(default='NULL', max_length=255)),
                ('Ingredients', models.CharField(max_length=255)),
            ],
        ),
    ]
