# Generated by Django 6.0.1 on 2026-01-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_product_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
    ]
