# Generated by Django 6.0.1 on 2026-01-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_product_description_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Discount', models.IntegerField()),
            ],
        ),
    ]
