# Generated by Django 6.0.1 on 2026-01-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
