# Generated by Django 6.0.1 on 2026-01-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
