# Generated by Django 6.0.1 on 2026-02-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Date',
        ),
    ]
